refactor(selection): replace using local directory for local file

diff --git a/src/lunaris-motion b/src/lunaris-motion
--- a/src/lunaris-motion
+++ b/src/lunaris-motion
@@ -26,7 +26,6 @@ mkdir -p "$LUNARIS_MOTION_CACHE_DIR"
 if [[ -f "$LUNARIS_MOTION_CONFIG_FILE" ]]; then
 	# shellcheck disable=SC1090
 	source "$LUNARIS_MOTION_CONFIG_FILE"
-	log "[INFO]: Using user configuration"
 fi
 # }}}
 
@@ -63,30 +62,17 @@ workshop() {
 
 # Local {{{
 
-local_video() {
-	local selected_video_file video_dir
-
-	# Check for video directory
-	if [[ -d "$LUNARIS_MOTION_CONFIG_VIDEO_DIR" ]]; then
-		video_dir="$LUNARIS_MOTION_CONFIG_VIDEO_DIR"
-	elif [[ -d "$(xdg-user-dir VIDEOS)/lunaris-motion" ]]; then
-		video_dir="$(xdg-user-dir VIDEOS)/lunaris-motion"
-	elif [[ -d "$HOME/Videos/lunaris-motion" ]]; then
-		video_dir="$HOME/Videos/lunaris-motion"
-	else
-		log "[ERROR]: Video directory is missing"
-		exit 1
-	fi
-
-	# Select Wallpaper
-	selected_video_file="$(rofi -config "$LUNARIS_MOTION_SYSTEM_DIR/rofi/lunaris-motion.rasi" \
-		-show filebrowser -filebrowser-directory "$video_dir" 2>/dev/null)"
-
-	# Exit safeguard
-	[[ -z "$selected_video_file" ]] && exit 0
+local_file() {
+	local selected_video_file
 
 	# Save selection on cache
-	printf '%s\n' "LUNARIS_MOTION_FILE=\"$selected_video_file\"" >"$LUNARIS_MOTION_CACHE_DIR/last"
+	if [[ -f "$video_file" ]]; then
+		selected_video_file="$(realpath "$video_file")"
+		printf '%s\n' "LUNARIS_MOTION_FILE=\"$selected_video_file\"" >"$LUNARIS_MOTION_CACHE_DIR/last"
+	else
+		log "[ERROR]: Video file is invalid"
+		exit 1
+	fi
 }
 # }}}
 
@@ -100,7 +86,7 @@ player() {
 		# shellcheck disable=SC1091
 		source "$LUNARIS_MOTION_CACHE_DIR/last"
 	else
-		log "[ERROR]: Cached selection is missing "
+		log "[ERROR]: Cached selection is missing"
 		exit 1
 	fi
 
@@ -111,16 +97,18 @@ player() {
 		player_config="$LUNARIS_MOTION_SYSTEM_DIR/mpv"
 	else
 		log "[ERROR]: Mpv configuration is missing"
+		exit 1
 	fi
 
 	# Check for existing video file
 	if [[ ! -f "$LUNARIS_MOTION_FILE" ]]; then
 		log "[ERROR]: Video selected is missing"
+		exit 1
 	fi
 
 	# Change video on existing player
 	if pgrep xwinwrap --quiet && [[ -S "$LUNARIS_MOTION_SOCKET_FILE" ]]; then
-		printf '{"command": ["loadfile", "%s", "replace"]}\n' "$LUNARIS_MOTION_FILE" | socat - UNIX-CONNECT:"$LUNARIS_MOTION_SOCKET_FILE" >/dev/null
+		player_replace
 	else
 		# Kill old instances
 		cleanup
@@ -160,6 +148,15 @@ player_pause() {
 	fi
 }
 
+player_replace() {
+	# Replace video
+	if [[ -S "$LUNARIS_MOTION_SOCKET_FILE" ]]; then
+		printf '{"command": ["loadfile", "%s", "replace"]}\n' "$LUNARIS_MOTION_FILE" | socat - UNIX-CONNECT:"$LUNARIS_MOTION_SOCKET_FILE" >/dev/null
+	else
+		return 1
+	fi
+}
+
 extract_frame() {
 	# Save frame on disk
 	if [[ -S "$LUNARIS_MOTION_SOCKET_FILE" ]]; then
@@ -174,7 +171,7 @@ extract_frame() {
 		while [[ ! -s "$LUNARIS_MOTION_FRAME_FILE" ]]; do
 			if ((SECONDS >= 10)); then
 				log "[ERROR]: Timed out waiting for frame"
-				exit 1
+				return 1
 			fi
 			sleep 1
 		done
@@ -219,7 +216,7 @@ USAGE:
 
 COMMANDS:
   -w|--workshop     Select video from workshop
-  -v|--video        Select video from local directory
+  -v|--video        Select video file
   -r|--restore      Restore cached wallpaper with daemon
   -d|--daemonless		Restore cached wallpaper without daemon
 
@@ -247,7 +244,8 @@ case "$1" in
 	;;
 
 -v | --video)
-	local_video
+	video_file="$2"
+	local_file
 	player
 	daemon
 	;;
